import os
import uuid
from fpdf import FPDF
from app.services.cloudinary_service import upload_image_to_cloudinary # We will reuse this or create a specialized one for PDFs
from app.services.llm_engine import generate_batch_name
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models.batch import Batch
from app.models.note import Note
from typing import Optional

class ProfessionalPDF(FPDF):
    def __init__(self, font_family="helvetica", *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.font_name = font_family

    def header(self):
        # Logo
        self.set_font(self.font_name, 'B', 20)
        self.set_text_color(30, 41, 59) # Slate 800
        self.cell(0, 10, 'DIGITAL SYNTHESIS REPORT', 0, 1, 'C')
        self.set_draw_color(226, 232, 240) # Slate 200
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font(self.font_name, 'I', 8)
        self.set_text_color(148, 163, 184) # Slate 400
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Curator AI Neural Pipeline', 0, 0, 'C')

def generate_professional_pdf(batch_name: str, notes_data: list) -> str:
    """
    Generates a truly professional, multi-page PDF from a batch of notes.
    Each note entry gets a clear heading and organized layout.
    """
    font_path = "C:/Windows/Fonts/arial.ttf"
    font_family = "helvetica"
    if os.path.exists(font_path):
        font_family = "Arial"

    pdf = ProfessionalPDF(font_family=font_family)
    if font_family == "Arial":
        try: pdf.add_font("Arial", "", font_path)
        except: font_family = "helvetica"; pdf.font_name = "helvetica"

    # --- TITLE PAGE ---
    pdf.add_page()
    pdf.set_font(font_family, 'B', 28)
    pdf.set_text_color(30, 41, 59)
    pdf.ln(60)
    pdf.cell(0, 20, "STUDY ARCHIVE", 0, 1, 'C')
    pdf.set_font(font_family, 'B', 20)
    pdf.set_text_color(71, 85, 105)
    pdf.multi_cell(0, 15, batch_name.upper(), 0, 'C')
    
    pdf.ln(20)
    pdf.set_font(font_family, 'I', 10)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 10, f"Total Compiled Entries: {len(notes_data)}", 0, 1, 'C')
    
    # --- NOTES CONTENT ---
    for i, note in enumerate(notes_data):
        pdf.add_page()
        
        # Section Header
        pdf.set_font(font_family, 'B', 14)
        pdf.set_text_color(37, 99, 235) # Blue 600
        pdf.cell(0, 10, f"ENTRY #{i+1}", 0, 1)
        pdf.set_draw_color(37, 99, 235)
        pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 40, pdf.get_y())
        pdf.ln(10)
        
        # Refined Text
        pdf.set_font(font_family, '', 11)
        pdf.set_text_color(51, 65, 85)
        
        # Robust parser for [B]...[/B] highlights
        content = note.refined_text or "No text extracted."
        parts = content.split('[B]')
        for j, part in enumerate(parts):
            if '[/B]' in part:
                segments = part.split('[/B]', 1)
                bold_part = segments[0]
                normal_part = segments[1] if len(segments) > 1 else ""
                
                # Bold style
                pdf.set_font(font_family, "B", 11)
                pdf.set_text_color(15, 23, 42) # Slate 900
                pdf.write(7, bold_part)
                # Normal style
                pdf.set_font(font_family, "", 11)
                pdf.set_text_color(51, 65, 85)
                pdf.write(7, normal_part)
            else:
                pdf.write(7, part)
        
        pdf.ln(15)

    temp_filename = f"note_archive_{uuid.uuid4()}.pdf"
    temp_dir = os.getenv("TEMP") if os.name == "nt" else "/tmp"
    if not temp_dir or not os.path.exists(temp_dir): temp_dir = "."
    temp_path = os.path.join(temp_dir, temp_filename)
    
    pdf.output(temp_path)
    return temp_path

async def sync_batch_document(db: AsyncSession, batch: Batch):
    """
    Re-synthesizes the combined text and synchronizes the PDF archive.
    """
    try:
        # Fetch all notes in order
        result = await db.execute(
            select(Note).where(Note.batch_id == batch.id).order_by(Note.created_at.asc())
        )
        notes = result.scalars().all()
        
        if not notes:
            return

        # 1. Combine Text
        combined = "\n\n--- NEXT ENTRY ---\n\n".join([n.refined_text for n in notes if n.refined_text])
        batch.combined_text = combined
        
        # 2. Auto-name if still default or too generic
        generic_names = ["Untitled Project", "Neural Synthesis Project", "Untitled Note Archive"]
        if not batch.name or batch.name in generic_names:
            batch.name = generate_batch_name(notes[0].refined_text)
        
        # 3. Generate PDF (Pass the notes list for multi-page structure)
        pdf_path = generate_professional_pdf(batch.name, notes)
        
        # 4. Upload to Cloudinary as a 'raw' file to ensure binary integrity
        with open(pdf_path, 'rb') as f:
            pdf_bytes = f.read()
            pdf_url = upload_image_to_cloudinary(
                pdf_bytes, 
                folder="project_reports", 
                resource_type="raw"
            )
            batch.pdf_url = pdf_url
            
        # Cleanup temp file
        if os.path.exists(pdf_path):
            try: os.remove(pdf_path)
            except: pass
                
    except Exception as e:
        print(f"CRITICAL: Batch Sync Failed: {str(e)}")
        
    await db.flush()
